services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    container_name: rust-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      APP_ENVIRONMENT: production
